### PR TITLE
redid PR to branch

### PR DESCRIPTION
**Pull request by highpost**
Hi @jeromecaisip, I redid the PR to your with-drf-setup branch. Please let me know if this works for you.

### CODE REVIEW

**Comment by jeromecaisip** [comment]
Hi. 
I think the changes are too far from the current branch. Sorry for the confusing workflow, but I think the best way to do this you could, start implementing changes from with-drf-setup branch instead of the master. Because the master contains other features aside from with-drf-setup

Then make a PR again to this branch.

**Comment by highpost** [comment]
By this you mean I should:

- delete my fork of jeromecaisip/cookiecutter-django-extended
- refork jeromecaisip/cookiecutter-django-extended
- clone it to my local machine
- set the branch on my *local* machine to with-drf-setup
- make my changes there
- push that back to my fork on GitHub
- create a PR for your repo, using your with-drf-setup branch

So my mistake was to not use your branch on my local machine. Right?

**Comment by jeromecaisip** [comment]
Hi @highpost. That is correct, because I used the master with additional stuff which are outside the scope of the original pull request to implement DRF. Sorry for the inconvenience. Or alternatively we can for the original pull request to be approved then you can make your changes from forking the original django-cookicutter repo.

Thanks

**Comment by highpost** [comment]
Let me try this one more time.

**Comment by highpost** [comment]
Hi Jerome,

I'm not sure where we're at, so I'm comfortable with backing out my PR and
waiting for yours to be approved. Just let me know.

--Dan

**Comment by jeromecaisip** [comment]
Hi. Sorry for the late response, I'm pretty busy at work. Anyways, I think it's better if we wait for the PR to be merged first, so all you updates would be streamlined with the main repo. Thanks!

**Comment by highpost** [comment]
Okay. I'll watch the repo.

**Pull request closed without merging**
